let books=[];let cart=JSON.parse(localStorage.getItem('hikayaty-cart')||'[]');
const $=id=>document.getElementById(id);const money=n=>`${Number(n).toFixed(0)} ج.م`;
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'حدث خطأ');return d}
async function loadBooks(q='',category=''){books=await api('/api/books?'+new URLSearchParams({q,category}));renderBooks();}
function renderBooks(list=books){$('bookGrid').innerHTML=list.map(b=>`<article class="book"><div class="cover"><span class="badge">${b.stock>0?'متاح':'نفد'}</span>${b.cover?`<img src="${b.cover}" alt="${b.title}" style="width:100%;height:100%;object-fit:cover">`:b.title.replace(/ /g,'<br>')}</div><h3>${b.title}</h3><div class="author">${b.author}</div><div class="price-row"><span class="price">${money(b.price)}</span><button class="add" ${b.stock<=0?'disabled':''} onclick="addToCart(${b.id})">🛒</button></div></article>`).join('')||'<p>لا توجد كتب مطابقة.</p>'}
function save(){localStorage.setItem('hikayaty-cart',JSON.stringify(cart));updateCart()}
function addToCart(id){const b=books.find(x=>x.id===id);const item=cart.find(x=>x.id===id);if(!b)return;if(item){if(item.qty>=b.stock)return alert('الكمية المتاحة غير كافية');item.qty++}else cart.push({id,qty:1});save();openCart()}
function updateCart(){ $('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);let total=0;$('cartItems').innerHTML=cart.length?cart.map(x=>{const b=books.find(y=>y.id===x.id);if(!b)return '';total+=b.price*x.qty;return `<div class="cart-line"><div class="thumb"></div><div class="grow"><strong>${b.title}</strong><div>${money(b.price)}</div><div class="qty"><button onclick="changeQty(${b.id},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${b.id},1)">+</button><button onclick="removeItem(${b.id})">حذف</button></div></div></div>`}).join(''):'<p style="text-align:center;padding:40px;color:#79686a">السلة فارغة حاليًا.</p>';$('cartTotal').textContent=money(total)}
function changeQty(id,d){const x=cart.find(y=>y.id===id),b=books.find(y=>y.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(y=>y.id!==id);else if(b&&x.qty>b.stock)x.qty=b.stock;save()}function removeItem(id){cart=cart.filter(y=>y.id!==id);save()}
function openCart(){$('cartDrawer').classList.add('open');$('overlay').classList.add('show');updateCart()}function closeCart(){$('cartDrawer').classList.remove('open');$('overlay').classList.remove('show')}
$('cartBtn').onclick=openCart;$('closeCart').onclick=closeCart;$('overlay').onclick=closeCart;
const accountTokenKey='hikayaty-account-token';
function showAccount(){const u=JSON.parse(localStorage.getItem('hikayaty-account-user')||'null');if(u){alert(`أهلًا ${u.name||u.email} 👋\nأنت مسجل الدخول بالفعل.`);return}$('accountModal').classList.add('show')}
$('accountBtn').onclick=showAccount;document.querySelector('[data-close]').onclick=()=>$('accountModal').classList.remove('show');
document.querySelectorAll('[data-account-tab]').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.account-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');const login=tab.dataset.accountTab==='login';$('loginForm').style.display=login?'block':'none';$('registerForm').style.display=login?'none':'block';});
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='جارٍ تسجيل الدخول...';try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('loginEmail').value.trim(),password:$('loginPassword').value})});localStorage.setItem(accountTokenKey,r.token);localStorage.setItem('hikayaty-account-user',JSON.stringify({name:r.name||r.email,email:r.email,role:r.role}));if(r.role==='admin'){location.href='/admin.html';return}$('loginMsg').textContent=`تم تسجيل الدخول بنجاح، أهلًا ${r.name||r.email} 👋`;setTimeout(()=>$('accountModal').classList.remove('show'),700)}catch(e){$('loginMsg').textContent=e.message}};
$('registerForm').onsubmit=async e=>{e.preventDefault();$('registerMsg').textContent='جارٍ إنشاء الحساب...';try{const r=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('registerName').value.trim(),email:$('registerEmail').value.trim(),phone:$('registerPhone').value.trim(),password:$('registerPassword').value})});localStorage.setItem(accountTokenKey,r.token);localStorage.setItem('hikayaty-account-user',JSON.stringify({name:r.name,email:r.email,role:r.role}));$('registerMsg').textContent='تم إنشاء الحساب وتسجيل الدخول بنجاح ✓';setTimeout(()=>$('accountModal').classList.remove('show'),700)}catch(e){$('registerMsg').textContent=e.message}};
document.querySelector('.search-toggle').onclick=()=>$('searchBar').classList.toggle('show');$('searchInput').addEventListener('input',e=>loadBooks(e.target.value));
document.querySelectorAll('.category-grid button').forEach(btn=>btn.onclick=()=>{document.getElementById('books').scrollIntoView({behavior:'smooth'});loadBooks('',btn.dataset.cat)});document.querySelector('.mobile-menu').onclick=()=>$('mobileNav').classList.toggle('show');
$('checkoutBtn').onclick=()=>{$('checkoutModal').classList.add('show');closeCart()};$('checkoutClose').onclick=()=>$('checkoutModal').classList.remove('show');
$('checkoutForm').onsubmit=async e=>{e.preventDefault();if(!cart.length)return alert('السلة فارغة');const f=new FormData(e.target);const items=cart.map(x=>({id:x.id,qty:x.qty}));$('checkoutMsg').textContent='جارٍ إنشاء الطلب...';try{const r=await api('/api/orders',{method:'POST',body:JSON.stringify({...Object.fromEntries(f.entries()),items})});cart=[];save();$('checkoutMsg').innerHTML=`تم إنشاء الطلب <strong>${r.order_no}</strong> بإجمالي ${money(r.total)}. ${r.payment.message}`;e.target.querySelector('button').disabled=true;}catch(err){$('checkoutMsg').textContent=err.message}};
$('adminLogin').onclick=async()=>{try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('adminEmail').value,password:$('adminPassword').value})});localStorage.setItem('hikayaty-admin-token',r.token);location.href='/admin.html'}catch(e){$('loginMsg').textContent=e.message}};
loadBooks();updateCart();
