require('dotenv').config();
const path=require('path');
const fs=require('fs');
const express=require('express');
const cors=require('cors');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const Database=require('better-sqlite3');
const multer=require('multer');

const app=express();
const PORT=Number(process.env.PORT||3000);
const ROOT=__dirname;
const db = new sqlite3.Database('./Hekaity.db');
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,phone TEXT NOT NULL,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS books(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,author TEXT NOT NULL,description TEXT DEFAULT '',price REAL NOT NULL,category TEXT NOT NULL,stock INTEGER NOT NULL DEFAULT 0,cover TEXT DEFAULT '',isbn TEXT DEFAULT '',active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,order_no TEXT UNIQUE NOT NULL,customer_name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT DEFAULT '',address TEXT NOT NULL,city TEXT NOT NULL,payment_method TEXT NOT NULL,payment_status TEXT NOT NULL DEFAULT 'pending',shipping_status TEXT NOT NULL DEFAULT 'pending',total REAL NOT NULL,shipping_fee REAL NOT NULL DEFAULT 0,tracking_no TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,book_id INTEGER NOT NULL,title TEXT NOT NULL,price REAL NOT NULL,qty INTEGER NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id));`);
const seedCount=db.prepare('SELECT COUNT(*) c FROM books').get().c;
if(!seedCount){const ins=db.prepare('INSERT INTO books(title,author,description,price,category,stock,cover,isbn) VALUES (?,?,?,?,?,?,?,?)');[['رسائل إلى الفقد','علي حسن','رواية أدبية عن الفقد والذاكرة.',180,'الروايات',25,'','978000000001'],['أوراق لا تحترق','ليلى عبد الله','نصوص عن الذاكرة وما يبقى من الحكايات.',195,'الروايات',18,'','978000000002'],['حين يتنصف الطريق','محمد الشاذلي','رحلة أدبية وتأملات في اختيارات الإنسان.',210,'الشعر والأدب',14,'','978000000003'],['في ممر الفقد','سارة الخطيب','رواية إنسانية عن التحول والمواجهة.',200,'الروايات',22,'','978000000004'],['ظلال الماضي','د. أحمد مراد','كتاب في التاريخ والذاكرة المصرية.',220,'التاريخ',11,'','978000000005']].forEach(x=>ins.run(...x));}
const adminEmail=process.env.ADMIN_EMAIL||'admin@hikayaty.com';
const adminPass=process.env.ADMIN_PASSWORD||'Hekayaty@2026!';
if(!db.prepare('SELECT 1 FROM admins WHERE email=?').get(adminEmail)) db.prepare('INSERT INTO admins(email,password_hash) VALUES(?,?)').run(adminEmail,bcrypt.hashSync(adminPass,12));

app.use(cors());app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));
const upload=multer({dest:path.join(ROOT,'uploads')});
fs.mkdirSync(path.join(ROOT,'uploads'),{recursive:true});
app.use('/uploads',express.static(path.join(ROOT,'uploads')));app.use(express.static(ROOT));
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer ')) throw 0;const payload=jwt.verify(h.slice(7),process.env.JWT_SECRET||'dev-secret');if(payload.role!=='admin') throw 0;req.admin=payload;next();}catch(e){res.status(401).json({error:'غير مصرح'});}}
function orderNo(){return 'HK'+Date.now().toString().slice(-8)+Math.floor(Math.random()*90+10);}
app.get('/api/books',(req,res)=>{const q=(req.query.q||'').trim();const cat=req.query.category||'';let sql='SELECT * FROM books WHERE active=1';const p=[];if(q){sql+=' AND (title LIKE ? OR author LIKE ? OR isbn LIKE ?)';p.push('%'+q+'%','%'+q+'%','%'+q+'%')}if(cat){sql+=' AND category=?';p.push(cat)}sql+=' ORDER BY id DESC';res.json(db.prepare(sql).all(...p));});
app.get('/api/categories',(req,res)=>res.json(db.prepare('SELECT category,COUNT(*) count FROM books WHERE active=1 GROUP BY category ORDER BY category').all()));
app.post('/api/auth/register',(req,res)=>{const {name,email,phone,password}=req.body;if(!name||!email||!phone||!password||String(password).length<6)return res.status(400).json({error:'أكمل بيانات الحساب واستخدم كلمة مرور 6 أحرف على الأقل'});if(db.prepare('SELECT 1 FROM customers WHERE email=?').get(email)||db.prepare('SELECT 1 FROM admins WHERE email=?').get(email))return res.status(409).json({error:'البريد الإلكتروني مستخدم بالفعل'});const r=db.prepare('INSERT INTO customers(name,email,phone,password_hash) VALUES(?,?,?,?)').run(name.trim(),email.trim().toLowerCase(),phone.trim(),bcrypt.hashSync(password,12));const c=db.prepare('SELECT id,name,email FROM customers WHERE id=?').get(r.lastInsertRowid);const token=jwt.sign({id:c.id,email:c.email,role:'customer',name:c.name},process.env.JWT_SECRET||'dev-secret',{expiresIn:'30d'});res.status(201).json({token,email:c.email,name:c.name,role:'customer'});});
app.post('/api/auth/login',(req,res)=>{const {email,password}=req.body;const a=db.prepare('SELECT * FROM admins WHERE email=?').get(email);if(a&&bcrypt.compareSync(password||'',a.password_hash)){const token=jwt.sign({id:a.id,email:a.email,role:'admin'},process.env.JWT_SECRET||'dev-secret',{expiresIn:'8h'});return res.json({token,email:a.email,name:'مدير الدار',role:'admin'});}const c=db.prepare('SELECT * FROM customers WHERE email=?').get(email);if(c&&bcrypt.compareSync(password||'',c.password_hash)){const token=jwt.sign({id:c.id,email:c.email,role:'customer',name:c.name},process.env.JWT_SECRET||'dev-secret',{expiresIn:'30d'});return res.json({token,email:c.email,name:c.name,role:'customer'});}return res.status(401).json({error:'البريد الإلكتروني أو كلمة المرور غير صحيحة'});});
app.get('/api/admin/me',auth,(req,res)=>res.json({email:req.admin.email}));
app.post('/api/admin/books',auth,(req,res)=>{const {title,author,description='',price,category,stock=0,cover='',isbn=''}=req.body;if(!title||!author||!category||price===undefined)return res.status(400).json({error:'بيانات الكتاب ناقصة'});const r=db.prepare('INSERT INTO books(title,author,description,price,category,stock,cover,isbn) VALUES(?,?,?,?,?,?,?,?)').run(title,author,description,Number(price),category,Number(stock),cover,isbn);res.json(db.prepare('SELECT * FROM books WHERE id=?').get(r.lastInsertRowid));});
app.put('/api/admin/books/:id',auth,(req,res)=>{const {title,author,description='',price,category,stock=0,cover='',isbn='',active=1}=req.body;db.prepare('UPDATE books SET title=?,author=?,description=?,price=?,category=?,stock=?,cover=?,isbn=?,active=? WHERE id=?').run(title,author,description,Number(price),category,Number(stock),cover,isbn,active?1:0,req.params.id);res.json(db.prepare('SELECT * FROM books WHERE id=?').get(req.params.id));});
app.delete('/api/admin/books/:id',auth,(req,res)=>{db.prepare('UPDATE books SET active=0 WHERE id=?').run(req.params.id);res.json({ok:true});});
app.post('/api/admin/upload',auth,upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({error:'لم يتم رفع ملف'});res.json({url:'/uploads/'+req.file.filename});});
app.get('/api/admin/orders',auth,(req,res)=>res.json(db.prepare('SELECT * FROM orders ORDER BY id DESC').all()));
app.patch('/api/admin/orders/:id',auth,(req,res)=>{const {payment_status,shipping_status,tracking_no}=req.body;db.prepare('UPDATE orders SET payment_status=COALESCE(?,payment_status),shipping_status=COALESCE(?,shipping_status),tracking_no=COALESCE(?,tracking_no) WHERE id=?').run(payment_status||null,shipping_status||null,tracking_no||null,req.params.id);res.json(db.prepare('SELECT * FROM orders WHERE id=?').get(req.params.id));});
app.get('/api/admin/stats',auth,(req,res)=>{res.json({books:db.prepare('SELECT COUNT(*) c FROM books WHERE active=1').get().c,orders:db.prepare('SELECT COUNT(*) c FROM orders').get().c,sales:db.prepare("SELECT COALESCE(SUM(total),0) s FROM orders WHERE payment_status='paid' OR payment_method='cod'").get().s});});
app.post('/api/orders',async(req,res)=>{const {customer_name,phone,email='',address,city,payment_method='cod',items=[]}=req.body;if(!customer_name||!phone||!address||!city||!Array.isArray(items)||!items.length)return res.status(400).json({error:'بيانات الطلب ناقصة'});let total=0;const rows=[];for(const item of items){const b=db.prepare('SELECT * FROM books WHERE id=? AND active=1').get(item.id);const qty=Math.max(1,Number(item.qty||1));if(!b||b.stock<qty)return res.status(400).json({error:`الكتاب غير متاح بالكمية المطلوبة: ${b?b.title:'غير معروف'}`});total+=b.price*qty;rows.push({b,qty});}const shipping=total>=500?0:50;total+=shipping;const no=orderNo();const tx=db.transaction(()=>{const r=db.prepare('INSERT INTO orders(order_no,customer_name,phone,email,address,city,payment_method,payment_status,total,shipping_fee) VALUES(?,?,?,?,?,?,?,?,?,?)').run(no,customer_name,phone,email,address,city,payment_method,payment_method==='cod'?'pending':'pending',total,shipping);const ins=db.prepare('INSERT INTO order_items(order_id,book_id,title,price,qty) VALUES(?,?,?,?,?)');const dec=db.prepare('UPDATE books SET stock=stock-? WHERE id=?');rows.forEach(x=>{ins.run(r.lastInsertRowid,x.b.id,x.b.title,x.b.price,x.qty);dec.run(x.qty,x.b.id);});return r.lastInsertRowid;});const id=tx();let payment={provider:payment_method,status:'pending',message:'تم إنشاء الطلب. ربط بوابة الدفع يحتاج مفاتيح الحساب في .env.'};if(payment_method==='cod')payment={provider:'cod',status:'pending',message:'سيتم الدفع عند الاستلام.'};res.status(201).json({order_id:id,order_no:no,total,payment});});
app.get('/api/orders/:orderNo',(req,res)=>{const o=db.prepare('SELECT * FROM orders WHERE order_no=?').get(req.params.orderNo);if(!o)return res.status(404).json({error:'الطلب غير موجود'});o.items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(o.id);res.json(o);});
app.get('/api/integrations/status',(req,res)=>res.json({paymob:!!process.env.PAYMOB_API_KEY,fawry:!!process.env.FAWRY_MERCHANT_CODE,bosta:!!process.env.BOSTA_API_KEY,wallets:!!process.env.PAYMOB_API_KEY}));
app.use((req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'Not found'});res.sendFile(path.join(ROOT,'index.html'));});
app.listen(PORT,()=>console.log(`Hikayaty running on http://localhost:${PORT}`));
